name: CI - Frontend

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: Lint & Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache frontend node modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  playwright-component:
    name: Playwright - Component tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache tests node modules
        uses: actions/cache@v4
        with:
          path: tests/node_modules
          key: ${{ runner.os }}-node-tests-${{ hashFiles('tests/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-tests-

      - name: Install test dependencies
        working-directory: tests
        run: npm ci

      - name: Install frontend dependencies
        run: npm --prefix frontend ci

      - name: Install Playwright browsers
        working-directory: tests
        run: npx playwright install --with-deps

      - name: Start frontend (Vite) on ct port
        run: npm --prefix frontend run dev -- --port 3100 &

      - name: Wait for frontend (port 3100)
        run: |
          for i in $(seq 1 30); do
            if curl -s http://localhost:3100 > /dev/null 2>&1; then
              echo "frontend ready"; exit 0
            fi
            sleep 1
          done
          echo "frontend did not become ready"; exit 1

      - name: Run component tests
        working-directory: tests
        run: npm run test:component

      - name: Upload component report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-component
          path: tests/playwright-report/component

  playwright-api:
    name: Playwright - API tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache tests node modules
        uses: actions/cache@v4
        with:
          path: tests/node_modules
          key: ${{ runner.os }}-node-tests-${{ hashFiles('tests/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-tests-

      - name: Install test dependencies
        working-directory: tests
        run: npm ci

      - name: Install backend dependencies
        run: npm --prefix backend ci

      - name: Start backend
        run: npm --prefix backend start &

      - name: Wait for backend (port 5000)
        run: |
          for i in $(seq 1 30); do
            if curl -s http://localhost:5000 > /dev/null 2>&1; then
              echo "backend ready"; exit 0
            fi
            sleep 1
          done
          echo "backend did not become ready"; exit 1

      - name: Install Playwright browsers
        working-directory: tests
        run: npx playwright install --with-deps

      - name: Run API tests
        working-directory: tests
        run: npm run test:api

      - name: Upload API report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-api
          path: tests/playwright-report/api

  playwright-e2e:
    name: Playwright - E2E tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache tests node modules
        uses: actions/cache@v4
        with:
          path: tests/node_modules
          key: ${{ runner.os }}-node-tests-${{ hashFiles('tests/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-tests-

      - name: Install test dependencies
        working-directory: tests
        run: npm ci

      - name: Install frontend dependencies
        run: npm --prefix frontend ci

      - name: Install backend dependencies
        run: npm --prefix backend ci

      - name: Start backend
        run: npm --prefix backend start &

      - name: Wait for backend (port 5000)
        run: |
          for i in $(seq 1 30); do
            if curl -s http://localhost:5000 > /dev/null 2>&1; then
              echo "backend ready"; exit 0
            fi
            sleep 1
          done
          echo "backend did not become ready"; exit 1

      - name: Install Playwright browsers
        working-directory: tests
        run: npx playwright install --with-deps

      - name: Run E2E tests
        working-directory: tests
        run: npm run test:e2e

      - name: Upload E2E report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-e2e
          path: tests/playwright-report/e2e
